# Generated by Django 4.1.5 on 2023-01-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('geolocation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Геолокация')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Имя человека',
                'verbose_name_plural': 'Имена людей',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='PersonAndImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_name', to='source.persons')),
                ('photo_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_photo', to='source.images')),
            ],
            options={
                'db_table': 'persons_and_images',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='persons_names',
            field=models.ManyToManyField(blank=True, related_name='persons_name', through='source.PersonAndImages', to='source.persons'),
        ),
    ]
